### ISSUE TITLE
SPM, CocoaPods, Carthage support

### ISSUE THREAD

**Issue by RomanPodymov** [weijentu/Higher-Order-Function-ObjC#1]
Hello.
Thank you for Higher-Order-Function-ObjC.
I know this repository was created for https://medium.com/@weijentu/higher-order-functions-in-objective-c-850f6c90de30, but it is also useful for all Objective-C developers. Do you want to add SPM, CocoaPods, Carthage support for Higher-Order-Function-ObjC?

**Comment by weijentu** [comment]
@RomanPodymov Hi Roman, you are welcome. As to SPM, CocoaPods or Carthage, I think yes. I'll try it in the near future👌
